#!/usr/bin/env node
/**
 * .env → js/env-config.generated.js 生成スクリプト
 * 
 * 用途: ローカルの .env ファイルから Firebase 設定や API キーを取得し、
 *       クライアント側の JS からアクセス可能な形式で書き出します。
 *       生成されたファイルは .gitignore 対象となり、Git にはコミットされません。
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const envPath = path.join(repoRoot, ".env");
const outputPath = path.join(repoRoot, "js", "env-config.generated.js");

// .env をパース
function parseEnv(content) {
  const result = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    // 引用符除去
    if ((value.startsWith('"') && value.endsWith('"'))
      || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  }
  return result;
}

// JS文字列エスケープ
function escapeJS(str) {
  return String(str || "")
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r");
}

function main() {
  let env = {};
  if (fs.existsSync(envPath)) {
    const content = fs.readFileSync(envPath, "utf-8");
    env = parseEnv(content);
    console.log(`[generate-config] Loaded ${Object.keys(env).length} entries from .env`);
  } else {
    console.warn("[generate-config] .env not found, using process.env or defaults");
    env = process.env;
  }

  const output = `// AUTO-GENERATED by scripts/generate-config.js - DO NOT EDIT MANUALLY
// This file is gitignored. Source of truth: .env
// Regenerate: \`npm run generate:config\`

export const ENV_CONFIG = Object.freeze({
  FIREBASE: {
    apiKey: "${escapeJS(env.FIREBASE_API_KEY)}",
    authDomain: "${escapeJS(env.FIREBASE_AUTH_DOMAIN)}",
    projectId: "${escapeJS(env.FIREBASE_PROJECT_ID)}",
    storageBucket: "${escapeJS(env.FIREBASE_STORAGE_BUCKET)}",
    messagingSenderId: "${escapeJS(env.FIREBASE_MESSAGING_SENDER_ID)}",
    appId: "${escapeJS(env.FIREBASE_APP_ID)}",
  },
  APP: {
    ALLOWED_GOOGLE_EMAIL: "${escapeJS(env.ALLOWED_GOOGLE_EMAIL)}",
  },
  AI: {
    sharedKeys: {
      gemini: "${escapeJS(env.GEMINI_API_KEY)}",
      openai: "${escapeJS(env.OPENAI_API_KEY)}",
    },
    defaultProvider: "${escapeJS(env.ACTIVE_AI_PROVIDER || 'gemini')}",
  },
  GENERATED_TIMESTAMP: "${new Date().toISOString()}",
});
`;

  fs.writeFileSync(outputPath, output, "utf-8");
  console.log(`[generate-config] Wrote config to ${outputPath}`);
}

main();
