#!/usr/bin/env node
/**
 * .env → js/ai-keys.generated.js 生成スクリプト
 *
 * 用途: 静的サイト配信前に .env の AI APIキーをクライアントJSへ注入する
 * 実行: `node scripts/generate-ai-keys.js` (または npm run dev/build 前に自動実行)
 *
 * 生成されたファイル (js/ai-keys.generated.js) は .gitignore 対象。
 * 存在しない場合は js/ai-config.js が空キーを返す (ローカル分析にフォールバック)
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const envPath = path.join(repoRoot, ".env");
const outputPath = path.join(repoRoot, "js", "ai-keys.generated.js");

// .env をパース (dotenv に依存せず最小実装)
function parseEnv(content) {
  const result = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    // 引用符除去
    if ((value.startsWith('"') && value.endsWith('"'))
      || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  }
  return result;
}

// JS文字列エスケープ (キーに特殊文字が入ってもXSSにならないように)
function escapeJSString(str) {
  return String(str || "")
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r");
}

function main() {
  let env = {};

  if (fs.existsSync(envPath)) {
    const content = fs.readFileSync(envPath, "utf-8");
    env = parseEnv(content);
    console.log(`[generate-ai-keys] Loaded ${Object.keys(env).length} entries from .env`);
  } else {
    console.log("[generate-ai-keys] .env not found, generating empty config");
  }

  const geminiKey = escapeJSString(env.GEMINI_API_KEY || "");
  const openaiKey = escapeJSString(env.OPENAI_API_KEY || "");

  const output = `// AUTO-GENERATED by scripts/generate-ai-keys.js - DO NOT EDIT MANUALLY
// This file is gitignored. Source of truth: .env
// Regenerate: \`npm run generate:keys\`

export const GENERATED_SHARED_KEYS = Object.freeze({
  gemini: "${geminiKey}",
  openai: "${openaiKey}",
});

export const GENERATED_TIMESTAMP = "${new Date().toISOString()}";
`;

  fs.writeFileSync(outputPath, output, "utf-8");
  console.log(`[generate-ai-keys] Wrote ${outputPath}`);
  console.log(`[generate-ai-keys]   gemini: ${geminiKey ? "✓ set" : "(empty)"}`);
  console.log(`[generate-ai-keys]   openai: ${openaiKey ? "✓ set" : "(empty)"}`);
}

main();
