#!/usr/bin/env node
/**
 * .env → js/env-config.generated.js 生成スクリプト
 * 
 * 用途: ローカルの .env ファイルから Firebase 設定や API キーを取得し、
 *       クライアント側の JS からアクセス可能な形式で書き出します。
 *       生成されたファイルは .gitignore 対象となり、Git にはコミットされません。
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const envPath = path.join(repoRoot, ".env");
const outputPath = path.join(repoRoot, "js", "env-config.generated.js");

// .env をパース
function parseEnv(content) {
  const result = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    // 引用符除去
    if ((value.startsWith('"') && value.endsWith('"'))
      || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  }
  return result;
}

// JS文字列エスケープ
function escapeJS(str) {
  return String(str || "")
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r");
}

// Firebase のクライアント設定は公開しても安全 (セキュリティはFirestoreルールで担保)
// .env に値がない場合は公開デフォルト値を使用し、Vercel等の環境でも Firebase を動作させる
const FIREBASE_DEFAULTS = {
  FIREBASE_API_KEY: "AIzaSyC1vcbD5ov1pgQvdb6CAIBFT4zi2mCwFxc",
  FIREBASE_AUTH_DOMAIN: "strokes-a0b62.firebaseapp.com",
  FIREBASE_PROJECT_ID: "strokes-a0b62",
  FIREBASE_STORAGE_BUCKET: "strokes-a0b62.firebasestorage.app",
  FIREBASE_MESSAGING_SENDER_ID: "13565861697",
  FIREBASE_APP_ID: "1:13565861697:web:54b8064f372730d3458bc0",
};

function main() {
  let env = {};
  if (fs.existsSync(envPath)) {
    const content = fs.readFileSync(envPath, "utf-8");
    env = parseEnv(content);
    console.log(`[generate-config] Loaded ${Object.keys(env).length} entries from .env`);
  } else {
    console.warn("[generate-config] .env not found, using process.env or defaults");
    env = process.env;
  }

  // Firebase: .env 優先、未設定ならデフォルト公開値を使用
  const fb = (k) => env[k] || FIREBASE_DEFAULTS[k] || "";

  const output = `// AUTO-GENERATED by scripts/generate-config.js - DO NOT EDIT MANUALLY
// This file is gitignored. Source of truth: .env
// Regenerate: \`npm run generate:config\`

export const ENV_CONFIG = Object.freeze({
  FIREBASE: {
    apiKey: "${escapeJS(fb('FIREBASE_API_KEY'))}",
    authDomain: "${escapeJS(fb('FIREBASE_AUTH_DOMAIN'))}",
    projectId: "${escapeJS(fb('FIREBASE_PROJECT_ID'))}",
    storageBucket: "${escapeJS(fb('FIREBASE_STORAGE_BUCKET'))}",
    messagingSenderId: "${escapeJS(fb('FIREBASE_MESSAGING_SENDER_ID'))}",
    appId: "${escapeJS(fb('FIREBASE_APP_ID'))}",
  },
  APP: {
    ALLOWED_GOOGLE_EMAIL: "${escapeJS(env.ALLOWED_GOOGLE_EMAIL)}",
  },
  AI: {
    sharedKeys: {
      gemini: "${escapeJS(env.GEMINI_API_KEY)}",
      openai: "${escapeJS(env.OPENAI_API_KEY)}",
    },
    defaultProvider: "${escapeJS(env.ACTIVE_AI_PROVIDER || 'gemini')}",
  },
  GENERATED_TIMESTAMP: "${new Date().toISOString()}",
});
`;

  fs.writeFileSync(outputPath, output, "utf-8");
  console.log(`[generate-config] Wrote config to ${outputPath}`);
}

main();
